# Bitcoin Scraper

    Scrape real-time Bitcoin data using this API https://min-api.cryptocompare.com/
    
    This scraper provides daily, hourly, and minute frequencies
    
    Fill out the API_KEY below to fetch the Bitcoin data

In [31]:
from datetime import datetime
import pandas as pd
import requests

def convertTimeStampToUTC(data):
    
  return datetime.fromtimestamp(data)
  
def getURL(apiKey, cryptoSymbol, frequency, timestamp, maxRecords):
    
  API_KEY = '&api_key=' + str(apiKey)
  limit = '&limit=' + str(maxRecords)
  header = 'fsym=' + str(cryptoSymbol)
  currency = '&tsym=USD'

  if (timestamp == ""):
    url = 'https://min-api.cryptocompare.com/data/v2/histo' + frequency + '?' + header
    
  else:  
    url = 'https://min-api.cryptocompare.com/data/v2/histo' + frequency + '?' + header + '&toTs=' + str(timestamp)

  return url + currency + API_KEY + limit  


def getCryptoData(apiKey, crypto, frequency, numOfRequests, maxRecords):
    
  numOfRequests = 5
  data = pd.DataFrame()
  nextTimeStamp = 0

  for i in range(0, numOfRequests):
    if (nextTimeStamp == 0):
      url = getURL(apiKey, crypto, frequency, "", maxRecords)
    
    else:
      url = getURL(apiKey, crypto, frequency, nextTimeStamp, maxRecords)

    response = requests.get(url).json()
    partialData = pd.DataFrame(response.get('Data').get('Data'))
    nextTimeStamp = partialData['time'].min() - 1
    data = pd.concat([data, partialData])

  data = data.sort_values(by = ['time'],ignore_index = True)
  data['timeUTC'] = data['time'].apply(convertTimeStampToUTC)
  data = data.reset_index(drop = True)
  return data

## Invoke Bitcoin Scraper

Get Hourly Bitcoin Rate

In [32]:
## Parameters to Scrape Bitcoin Data

## API_KEY: Create a API_KEY by signing up for a free trial account at https://min-api.cryptocompare.com/
## Valid values for cryptocurrency: BTC | ETH | XRP | BCH | BSV | LTC | EOS | ADA | XMR 
## numOfRequests: For a trial account, this is approximately 1000 per second
## maxRecords: The max records is 2000
## frequency : Valid options are Day | Hour | Minute

API_KEY = ""
crypto = "BTC"
numOfRequests = 5
maxRecords = 200
frequency = "hour"

cryptoData = getCryptoData(API_KEY, crypto, frequency, numOfRequests, maxRecords)
cryptoData

,time,high,low,open,volumefrom,volumeto,close,conversionType,conversionSymbol,timeUTC
0,1598943600,11939.37,11866.31,11867.32,2875.36,34218454.48,11924.93,direct,,2020-09-01 00:00:00
1,1598947200,11943.61,11881.94,11924.93,1719.28,20484981.51,11921.29,direct,,2020-09-01 01:00:00
2,1598950800,11956.69,11874.51,11921.29,1705.99,20345125.74,11948.76,direct,,2020-09-01 02:00:00
3,1598954400,11954.61,11920.08,11948.76,1445.10,17242558.78,11930.79,direct,,2020-09-01 03:00:00
4,1598958000,11930.79,11859.62,11930.79,1457.14,17329159.86,11877.62,direct,,2020-09-01 04:00:00
...,...,...,...,...,...,...,...,...,...,...
1000,1602543600,11663.65,11500.51,11662.69,3957.50,45736215.27,11539.76,direct,,2020-10-12 16:00:00
1001,1602547200,11550.20,11447.45,11539.76,2016.67,23177887.30,11496.19,direct,,2020-10-12 17:00:00
1002,1602550800,11516.58,11459.73,11496.19,1141.83,13102250.22,11511.15,direct,,2020-10-12 18:00:00
1003,1602554400,11511.53,11462.01,11511.15,1281.04,14708235.18,11491.95,direct,,2020-10-12 19:00:00
1004,1602558000,11491.96,11433.47,11491.95,1354.14,15507676.24,11465.44,direct,,2020-10-12 20:00:00

Get Daily Bitcoin Rate

In [33]:
API_KEY = ""
crypto = "BTC"
numOfRequests = 5
maxRecords = 200
frequency = "day"

cryptoData = getCryptoData(API_KEY, crypto, frequency, numOfRequests, maxRecords)
cryptoData

,time,high,low,open,volumefrom,volumeto,close,conversionType,conversionSymbol,timeUTC
0,1515801600,14595.04,13830.28,13841.19,71300.93,1.021353e+09,14243.12,direct,,2018-01-12 16:00:00
1,1515888000,14415.67,13031.91,14244.12,81536.00,1.112591e+09,13638.63,direct,,2018-01-13 16:00:00
2,1515974400,14355.82,13416.71,13638.63,84089.84,1.170463e+09,13631.98,direct,,2018-01-14 16:00:00
3,1516060800,13648.84,10032.69,13634.60,325702.79,3.842652e+09,11282.49,direct,,2018-01-15 16:00:00
4,1516147200,11736.30,9205.38,11282.49,348631.94,3.666978e+09,11162.70,direct,,2018-01-16 16:00:00
...,...,...,...,...,...,...,...,...,...,...
1000,1602201600,11109.32,10839.30,10929.40,32665.61,3.598024e+08,11058.78,direct,,2020-10-08 17:00:00
1001,1602288000,11485.43,11057.98,11058.78,26181.83,2.969258e+08,11301.57,direct,,2020-10-09 17:00:00
1002,1602374400,11434.10,11284.09,11301.57,17795.07,2.021310e+08,11375.51,direct,,2020-10-10 17:00:00
1003,1602460800,11725.28,11223.99,11375.51,41705.77,4.785571e+08,11539.76,direct,,2020-10-11 17:00:00
1004,1602547200,11550.20,11433.47,11539.76,5797.60,6.654139e+07,11465.44,direct,,2020-10-12 17:00:00

Get Every Minute of Bitcoin Price

In [34]:
API_KEY = ""
crypto = "BTC"
numOfRequests = 5
maxRecords = 200
frequency = "minute"

cryptoData = getCryptoData(API_KEY, crypto, frequency, numOfRequests, maxRecords)
cryptoData

,time,high,low,open,volumefrom,volumeto,close,conversionType,conversionSymbol,timeUTC
0,1602500760,11259.09,11255.20,11259.09,35.440,398876.80,11257.02,direct,,2020-10-12 04:06:00
1,1602500820,11258.25,11254.90,11257.02,29.370,330605.72,11256.62,direct,,2020-10-12 04:07:00
2,1602500880,11256.79,11248.07,11256.62,23.930,269241.05,11248.07,direct,,2020-10-12 04:08:00
3,1602500940,11255.07,11248.07,11248.07,18.270,205553.29,11255.03,direct,,2020-10-12 04:09:00
4,1602501000,11256.75,11253.75,11255.03,12.710,143079.29,11254.02,direct,,2020-10-12 04:10:00
...,...,...,...,...,...,...,...,...,...,...
1000,1602560760,11465.07,11462.38,11463.49,15.480,177568.92,11464.22,direct,,2020-10-12 20:46:00
1001,1602560820,11464.22,11459.91,11464.22,6.392,73288.15,11461.71,direct,,2020-10-12 20:47:00
1002,1602560880,11464.15,11461.71,11461.71,9.385,107622.29,11463.28,direct,,2020-10-12 20:48:00
1003,1602560940,11467.09,11460.39,11463.28,37.130,425759.81,11460.39,direct,,2020-10-12 20:49:00
1004,1602561000,11465.76,11460.39,11460.39,0.000,0.00,11465.76,direct,,2020-10-12 20:50:00