## Scrape CryptoCurrency
    
    Scrape Bitcoin data real-time using this API https://min-api.cryptocompare.com/
    
    1. Create a free trial account
    2. Create a free token and fill it here
    3. Fetch latest Bitcoin data
 
## Bitcoin Scraper

In [1]:
from datetime import datetime
import pandas as pd
import requests

def convertTimeStampToUTC(data):
    
  from datetime import datetime
  return datetime.fromtimestamp(data)
  
def getURL(apiKey, cryptoSymbol, frequency, timestamp, maxRecords):
    
  API_KEY = '&api_key=' + str(apiKey)
  limit = '&limit=' + str(maxRecords)
  header = 'fsym=' + str(cryptoSymbol)
  currency = '&tsym=USD'

  if (timestamp == ""):
    url = 'https://min-api.cryptocompare.com/data/v2/histo' + frequency + '?' + header
    
  else:  
    url = 'https://min-api.cryptocompare.com/data/v2/histo' + frequency + '?' + header + '&toTs=' 
    + str(timestamp)

  return url + currency + API_KEY + limit  


def getCryptoData(apikey, crypto, frequency, numOfRequests, maxRecords):
    
  numOfRequests = 5
  data = pd.DataFrame()
  nextTimeStamp = 0

  for i in range(0, numOfRequests):
    if (nextTimeStamp == 0):
      url = getURL(apikey, crypto, frequency, "", maxRecords)
    
    else:
      url = getURL(apikey, crypto, frequency, nextTimeStamp, maxRecords)

    response = requests.get(url).json()
    partialData = pd.DataFrame(response.get('Data').get('Data'))
    nextTimeStamp = partialData['time'].min() - 1
    data = pd.concat([data, partialData])

  data = data.sort_values(by = ['time'],ignore_index = True)
  data['timeUTC'] = data['time'].apply(convertTimeStampToUTC)
  data = data.reset_index(drop = True)
  return data

## Invoke Bitcoin Scraper

Get Hourly Bitcoin Rate

In [3]:
## Parameters to Scrape Bitcoin Data

## API_KEY: Create a API_KEY by signing up for a free trial account at https://min-api.cryptocompare.com/
## Valid values for cryptocurrency: BTC | ETH | XRP | BCH | BSV | LTC | EOS | ADA | XMR 
## numOfRequests: For a trial account, this is approximately 1000 per second
## maxRecords: The max records is 2000
## frequency : Valid options are Day | Hour | Minute

API_KEY = ""
crypto = "BTC"
numOfRequests = 5
maxRecords = 200
frequency = "hour"

cryptoData = getCryptoData(API_KEY, crypto, frequency, numOfRequests, maxRecords)
cryptoData

,time,high,low,open,volumefrom,volumeto,close,conversionType,conversionSymbol,timeUTC
0,1594252800,9441.67,9400.10,9439.20,966.70,9100378.96,9411.58,direct,,2020-07-08 17:00:00
1,1594256400,9412.21,9385.88,9411.58,959.98,9018508.76,9385.88,direct,,2020-07-08 18:00:00
2,1594260000,9405.24,9364.31,9385.88,1137.18,10670873.01,9384.01,direct,,2020-07-08 19:00:00
3,1594263600,9389.45,9373.48,9384.01,517.83,4855750.67,9388.99,direct,,2020-07-08 20:00:00
4,1594267200,9403.01,9376.76,9388.99,512.28,4806153.03,9387.56,direct,,2020-07-08 21:00:00
...,...,...,...,...,...,...,...,...,...,...
1000,1597852800,11793.03,11673.26,11741.29,2506.90,29404375.84,11754.98,direct,,2020-08-19 09:00:00
1001,1597856400,11786.27,11724.37,11754.98,1656.51,19473562.17,11786.27,direct,,2020-08-19 10:00:00
1002,1597860000,11786.89,11663.81,11786.27,2745.85,32164552.93,11736.36,direct,,2020-08-19 11:00:00
1003,1597863600,11752.78,11653.56,11736.36,2106.07,24650479.31,11668.66,direct,,2020-08-19 12:00:00
1004,1597867200,11723.26,11592.20,11668.66,2380.99,27753768.34,11692.50,direct,,2020-08-19 13:00:00

Get Daily Bitcoin Rate

In [4]:
API_KEY = ""
crypto = "BTC"
numOfRequests = 5
maxRecords = 200
frequency = "day"

cryptoData = getCryptoData(API_KEY, crypto, frequency, numOfRequests, maxRecords)
cryptoData

,time,high,low,open,volumefrom,volumeto,close,conversionType,conversionSymbol,timeUTC
0,1511049600,8100.87,7675.41,7781.02,68618.85,5.413913e+08,8042.64,direct,,2017-11-18 16:00:00
1,1511136000,8294.12,7947.28,8042.64,75703.64,6.173543e+08,8244.69,direct,,2017-11-19 16:00:00
2,1511222400,8368.36,7819.06,8245.87,115454.28,9.383454e+08,8099.97,direct,,2017-11-20 16:00:00
3,1511308800,8304.37,8091.63,8099.92,65811.68,5.396974e+08,8234.55,direct,,2017-11-21 16:00:00
4,1511395200,8266.55,8012.35,8234.50,68010.70,5.554651e+08,8013.41,direct,,2017-11-22 16:00:00
...,...,...,...,...,...,...,...,...,...,...
1000,1597449600,11981.62,11697.88,11774.52,31094.75,3.692582e+08,11860.91,direct,,2020-08-14 17:00:00
1001,1597536000,11934.96,11701.22,11860.91,22029.01,2.607169e+08,11917.97,direct,,2020-08-15 17:00:00
1002,1597622400,12474.73,11775.66,11917.97,56064.01,6.821701e+08,12301.19,direct,,2020-08-16 17:00:00
1003,1597708800,12397.40,11855.24,12301.19,49904.68,6.042460e+08,11956.69,direct,,2020-08-17 17:00:00
1004,1597795200,12021.80,11592.20,11956.69,46216.80,5.446298e+08,11741.27,direct,,2020-08-18 17:00:00

Get Every Minute of Bitcoin Price

In [6]:
API_KEY = ""
crypto = "BTC"
numOfRequests = 5
maxRecords = 200
frequency = "minute"

cryptoData = getCryptoData(API_KEY, crypto, frequency, numOfRequests, maxRecords)
cryptoData

,time,high,low,open,volumefrom,volumeto,close,conversionType,conversionSymbol,timeUTC
0,1595666700,9598.27,9597.42,9597.42,4.775,45865.71,9598.08,direct,,2020-07-25 01:45:00
1,1595666760,9609.05,9599.26,9606.08,626.940,6024296.52,9609.05,invert_divide,ETH,2020-07-25 01:46:00
2,1595666820,9598.42,9597.37,9597.47,9.988,95907.21,9598.42,direct,,2020-07-25 01:47:00
3,1595666880,9602.85,9598.42,9598.42,20.190,193903.53,9602.85,direct,,2020-07-25 01:48:00
4,1595666940,9604.98,9602.85,9602.85,11.670,112139.89,9604.61,direct,,2020-07-25 01:49:00
...,...,...,...,...,...,...,...,...,...,...
1000,1595726700,9685.78,9685.16,9685.73,5.240,50762.43,9685.16,direct,,2020-07-25 18:25:00
1001,1595726760,9696.43,9690.01,9690.21,240.300,2328509.32,9690.01,invert_divide,ETH,2020-07-25 18:26:00
1002,1595726820,9689.89,9681.86,9690.01,666.090,6454337.26,9689.89,invert_divide,ETH,2020-07-25 18:27:00
1003,1595726880,9681.60,9681.06,9681.06,4.504,43645.34,9681.60,direct,,2020-07-25 18:28:00
1004,1595726940,9681.71,9681.60,9681.60,0.000,0.00,9681.71,direct,,2020-07-25 18:29:00